version: '3.9'

services:
  bookmark:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 024Wisdom@29
      POSTGRES_DB: Bookmark
    networks:
      - nest-bookmark

networks:
  nest-bookmark:
